In [2]:
from dataclasses import dataclass
import itertools
import logging
import random
import math
import numpy as np
import json
import pickle
import time
import torch
import sys
import pdb
import os
os.chdir("/Users/guotianyu/GitHub/birth")

from omegaconf import OmegaConf
from pathlib import Path
from torch import nn, Tensor
from torch.nn import functional as F
from typing import List, Optional, Tuple

from data import DataArgs, Dataset, iterate_batches, MetaProcess
from ihead_full_model import ModelArgs, Transformer
%load_ext autoreload
%autoreload 2

In [3]:
ds = MetaProcess(DataArgs())

In [4]:
ds.bos_num

1

In [5]:
import pickle

meta_processed = ds.process()

with open('data/meta_bos1_d1.pickle', 'wb') as handle:
    pickle.dump(meta_processed, handle, protocol=pickle.HIGHEST_PROTOCOL)



In [15]:
x_exp, out_exp = ds.gen_batch(np.random.default_rng(0), 128)
x_exp

array([[65, 50, 39, ..., 54, 50, 43],
       [65, 58,  1, ..., 66, 47, 52],
       [65, 57, 47, ...,  1, 39, 63],
       ...,
       [65, 59, 57, ...,  6,  1, 47],
       [65,  6,  1, ..., 57, 53, 61],
       [65, 39, 56, ..., 46,  1, 51]])

In [14]:
np.where(x_exp == 66)

(array([  0,   0,   0, ..., 127, 127, 127]),
 array([ 27,  74,  78, ..., 232, 240, 251]))

In [29]:
import pickle
import numpy as np

with open("/Users/guotianyu/GitHub/birth/data/meta_bos1_d_random.pickle", "rb") as f:
    meta_info = pickle.load(f)



In [25]:
meta_info.keys()

dict_keys(['marginal', 'cond', 'itos', 'stoi', 'vocab_size', 'bos_num', 'delimiter_p', 'bos', 'delimiter'])

In [30]:
# meta_info['marginal']
np.sort(meta_info['marginal'])

array([0.00000000e+00, 0.00000000e+00, 8.96544181e-07, 2.68963254e-06,
       2.42066929e-05, 1.00412948e-04, 1.77515748e-04, 2.07101706e-04,
       2.86894138e-04, 3.19169728e-04, 4.74271872e-04, 5.45995406e-04,
       5.63029746e-04, 7.15442256e-04, 1.42012598e-03, 1.47122900e-03,
       1.54026290e-03, 1.61108989e-03, 1.70074431e-03, 1.87288079e-03,
       1.94729396e-03, 2.15080949e-03, 2.20729177e-03, 2.47535848e-03,
       2.54618547e-03, 2.75059755e-03, 2.97025087e-03, 3.16480096e-03,
       3.25266229e-03, 3.42479877e-03, 3.47500524e-03, 4.05506933e-03,
       4.36527362e-03, 4.55354789e-03, 4.91395865e-03, 5.41602340e-03,
       5.54691885e-03, 6.28925743e-03, 6.35470515e-03, 6.98676880e-03,
       7.01007895e-03, 7.06925087e-03, 9.24874977e-03, 9.68984951e-03,
       1.01497767e-02, 1.06079107e-02, 1.19742441e-02, 1.40067097e-02,
       1.41385017e-02, 1.57657294e-02, 1.77928158e-02, 1.83325354e-02,
       1.99418322e-02, 2.38337305e-02, 2.81138324e-02, 2.98898864e-02,
      

In [22]:
meta_info['stoi']['.']

8